version: "3"

services:
  app:
    image: stsaens/resume
    build: .
    container_name: resume
    restart: always
    environment:
      - VIRTUAL_HOST=resume.jungmin.kim
      - VIRTUAL_PORT=6060
    networks:
      - nginx-proxy
      - default
networks:
  nginx-proxy:
    external:
      name: nginx-proxy
