version: "3"

services:
  app:
    image: stsaens/resume
    build: .
    container_name: resume
    restart: always
    environment:
      VIRTUAL_HOST: resume.jungmin.kim
      VIRTUAL_PORT: 6060
      LETSENCRYPT_HOST: resume.jungmin.kim
      LETSENCRYPT_EMAIL: icarmenjm@gmail.com
    networks:
      - nginx-proxy
      - default
networks:
  nginx-proxy:
    external:
      name: nginx-proxy
